/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as http from "../http.js";
import type * as inventories from "../inventories.js";
import type * as material_audit_logs from "../material_audit_logs.js";
import type * as material_versions from "../material_versions.js";
import type * as materials from "../materials.js";
import type * as transactions from "../transactions.js";
import type * as transactions_details from "../transactions_details.js";
import type * as types from "../types.js";
import type * as users from "../users.js";
import type * as warehouses from "../warehouses.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  http: typeof http;
  inventories: typeof inventories;
  material_audit_logs: typeof material_audit_logs;
  material_versions: typeof material_versions;
  materials: typeof materials;
  transactions: typeof transactions;
  transactions_details: typeof transactions_details;
  types: typeof types;
  users: typeof users;
  warehouses: typeof warehouses;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
